/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Linter file = new Linter();
        String returnString = Linter.linter("src/main/resources/gates.js");
        System.out.println(returnString);
    }
    
}
